import type { Member } from "@/lib/types";

export const DEMO_MEMBERS: Member[] = [
  {
    id: "demo-dani-cruz",
    profile: {
      name: "Dani Cruz",
      memberType: "artist",
      city: "Los Angeles",
      neighborhood: "Boyle Heights",
      discipline: "Muralist",
      yearsExperience: "8",
      category: "Mural",
      subcategory: "Bilingual",
      approvedBlurb:
        "Boyle Heights muralist working with local schools and small businesses to tell neighborhood stories in big color.",
      services: ["Murals", "Sign painting", "Workshops"],
      venueTypes: ["Storefronts", "Schools", "Community centers"],
      vibe: "Loud color, slow work, lots of pan dulce.",
      instagramHandle: "danicruz",
      latitude: 34.0339,
      longitude: -118.2098,
    },
  },
  {
    id: "demo-kira-wave",
    profile: {
      name: "Kira Wave",
      memberType: "artist",
      city: "Los Angeles",
      neighborhood: "Silver Lake",
      discipline: "Sound artist",
      yearsExperience: "6",
      category: "Music",
      subcategory: "Late night",
      approvedBlurb:
        "Coffee, tacos, hidden patios — Kira posts the calmest, weirdest pressed-vinyl morning sets in town.",
      services: ["DJ sets", "Sound design", "Live shows"],
      venueTypes: ["Coffee shops", "Galleries", "Backyards"],
      vibe: "If a record skips in a room and nobody's bothered, that's the vibe.",
      instagramHandle: "kirawave",
      spotifyUrl: "https://open.spotify.com/user/kirawave",
      latitude: 34.0869,
      longitude: -118.2702,
    },
  },
  {
    id: "demo-south-la-mutual-aid",
    profile: {
      name: "South LA Mutual Aid",
      memberType: "organizer",
      city: "Los Angeles",
      neighborhood: "South LA",
      category: "Community",
      subcategory: "Mutual aid",
      cause: "Neighbors caring for neighbors. Weekly grocery drops, rental support, rapid-response funds.",
      approvedBlurb:
        "Volunteer-run neighborhood coordinating weekly grocery drops, rental support, and rapid-response funds across South LA.",
      serves: ["individuals"],
      needsMost: ["Volunteer drivers", "Pantry donations", "Bilingual organizers"],
      connectWith: ["Local churches", "Restaurants", "Schools"],
      shareTypes: ["Groceries", "Rent assistance", "Rides"],
      instagramHandle: "southlamutualaid",
      latitude: 33.9803,
      longitude: -118.3092,
    },
  },
  {
    id: "demo-casa-verde",
    profile: {
      name: "Casa Verde Plant Co",
      memberType: "organizer",
      city: "Los Angeles",
      neighborhood: "Highland Park",
      category: "Community",
      subcategory: "Garden collective",
      cause: "Family-run plant shop and propagation studio. We grow, you grow.",
      approvedBlurb:
        "Family-run plant shop and propagation studio. We grow, you grow.",
      serves: ["small-businesses", "individuals"],
      needsMost: ["Pot donations", "Composting partners"],
      connectWith: ["Schools", "Community gardens"],
      shareTypes: ["Cuttings", "Workshops", "Pots"],
      businessName: "Casa Verde Plant Co",
      businessAddress: "5634 N Figueroa St, Los Angeles, CA",
      businessHours: "Wed–Sun · 11am – 6pm",
      businessPhone: "+1 (323) 555-0188",
      websiteUrl: "casaverde.la",
      instagramHandle: "casaverdeplantco",
      latitude: 34.1133,
      longitude: -118.1925,
    },
  },
  {
    id: "demo-courtside-sports-bar",
    profile: {
      name: "Courtside Sports Bar",
      memberType: "vendor",
      city: "Los Angeles",
      neighborhood: "Downtown LA",
      category: "Food & Drink",
      subcategory: "Sports Bar",
      businessName: "Courtside Sports Bar",
      approvedBlurb:
        "12 big screens, the league pass on every night, and the loudest Lakers crowd downtown.",
      services: ["Full bar", "Wings", "Big screens"],
      vibe: "Jerseys on the walls, every game on, half-time shots.",
      businessAddress: "420 W 7th St, Los Angeles, CA",
      businessHours: "Daily · 11am – 1am",
      instagramHandle: "courtsidela",
      latitude: 34.0481,
      longitude: -118.2575,
    },
  },
  {
    id: "demo-el-tri-cantina",
    profile: {
      name: "El Tri Cantina",
      memberType: "vendor",
      city: "Los Angeles",
      neighborhood: "Boyle Heights",
      category: "Food & Drink",
      subcategory: "Mexican Bar",
      businessName: "El Tri Cantina",
      approvedBlurb:
        "El Tri on every screen. Micheladas, tacos al pastor, and the whole barrio in green when Mexico plays.",
      services: ["Micheladas", "Tacos", "Soccer on every screen"],
      vibe: "Verde, blanco y rojo — sing every anthem.",
      businessAddress: "1801 E Cesar E Chavez Ave, Los Angeles, CA",
      businessHours: "Daily · 10am – 12am",
      instagramHandle: "eltricantina",
      latitude: 34.0444,
      longitude: -118.2007,
    },
  },
  {
    id: "demo-azteca-grill",
    profile: {
      name: "Azteca Grill & Bar",
      memberType: "vendor",
      city: "Los Angeles",
      neighborhood: "East LA",
      category: "Food & Drink",
      subcategory: "Mexican Bar",
      businessName: "Azteca Grill & Bar",
      approvedBlurb:
        "Family-run grill that turns into a Mexico supporters' club on match day. Parrillada + penalties.",
      services: ["Parrillada", "Cerveza", "Match-day specials"],
      vibe: "Abuela's cooking, tío's commentary.",
      businessAddress: "5450 Whittier Blvd, Los Angeles, CA",
      businessHours: "Daily · 9am – 11pm",
      instagramHandle: "aztecagrillla",
      latitude: 34.0224,
      longitude: -118.1745,
    },
  },
  {
    id: "demo-the-corner-tap",
    profile: {
      name: "The Corner Tap",
      memberType: "vendor",
      city: "Los Angeles",
      neighborhood: "Echo Park",
      category: "Food & Drink",
      subcategory: "Sports Bar",
      businessName: "The Corner Tap",
      approvedBlurb:
        "Neighborhood pub with craft taps and a projector screen that comes down for every big game.",
      services: ["Craft beer", "Projector screen", "Trivia nights"],
      vibe: "Low-key, cold pints, good sightlines.",
      businessAddress: "1533 Sunset Blvd, Los Angeles, CA",
      businessHours: "Daily · 12pm – 2am",
      instagramHandle: "cornertapla",
      latitude: 34.0782,
      longitude: -118.2606,
    },
  },
  {
    id: "demo-highland-pub",
    profile: {
      name: "Highland Pub",
      memberType: "vendor",
      city: "Los Angeles",
      neighborhood: "Highland Park",
      category: "Food & Drink",
      subcategory: "Sports Bar",
      businessName: "Highland Pub",
      approvedBlurb:
        "Old-school pub with a brand-new wall of TVs. NBA, NFL, and Premier League mornings with full English.",
      services: ["Draft beer", "Pub grub", "Premier League mornings"],
      vibe: "Wood booths, scarves on the wall, proper banter.",
      businessAddress: "5681 N Figueroa St, Los Angeles, CA",
      businessHours: "Daily · 8am – 12am",
      instagramHandle: "highlandpubla",
      latitude: 34.1119,
      longitude: -118.1916,
    },
  },
];

export function getDemoMember(id: string): Member | undefined {
  return DEMO_MEMBERS.find((m) => m.id === id);
}
